### PR TITLE
V4.7.0 patch reduction 2

### PR DESCRIPTION
**Pull request by jsomervi**
Clarified commit log for logfile commit
Fixed code comment in 50 to 10 mS reduction commit

### CODE REVIEW

**Review by saulwold — COMMENTED** [review]
This comment is not a blocker, but would it make sense to remove the 2 systemd service file changes and create a libvirt-config package similar to what we did with other services?  Maybe this could be a future change.

**Comment by jsomervi** [comment]
> This comment is not a blocker, but would it make sense to remove the 2 systemd service file changes and create a libvirt-config package similar to what we did with other services? Maybe this could be a future change.

Yes, I think that would make sense.

Anything left outstanding here Saul?

**Comment by saulwold** [comment]
> > This comment is not a blocker, but would it make sense to remove the 2 systemd service file changes and create a libvirt-config package similar to what we did with other services? Maybe this could be a future change.
> 
> Yes, I think that would make sense.
> 
> Anything left outstanding here Saul?

No, but if you could open a story for the libvirt-config that would be great, thanks

**Review by saulwold — APPROVED** [review]

**Comment by jsomervi** [comment]
> > > This comment is not a blocker, but would it make sense to remove the 2 systemd service file changes and create a libvirt-config package similar to what we did with other services? Maybe this could be a future change.
> > 
> > 
> > Yes, I think that would make sense.
> > Anything left outstanding here Saul?
> 
> No, but if you could open a story for the libvirt-config that would be great, thanks

Story 2005511

**Pull request merged**
